### ISSUE TITLE
All zero results with 3D fields

### ISSUE THREAD

**Issue by ecutolo** [gher-ulg/divand.py#2]
Hi, 
I'm trying to use DIVAnd.py with a 3d field so I just adapted one of the example written in JULIA to check if it works but I just obtain a zero fields. Here is the code I used:
```
from julia import DIVAnd
import numpy as np

x = np.random.rand(75);
y = np.random.rand(75);
z = np.random.rand(75);
f = np.sin(x*6) * np.cos(y*6)+np.sin(z*6) * np.cos(x*6) ;

testsize=300
testsizez=3
xi,yi,zi = np.meshgrid(np.arange(0,1,1/testsize),np.arange(0,1,1/testsize),np.arange(0,1,1/testsizez));

fref = np.sin(xi*6) * np.cos(yi*6)+np.sin(zi*6) * np.cos(xi*6) ;

mask = np.ones(xi.shape)==1;

pm = np.ones(xi.shape) / (xi[1,2,1]-xi[1,1,1])
pn = np.ones(xi.shape) / (yi[2,1,1]-yi[1,1,1])
po = np.ones(xi.shape) / (zi[1,1,2]-zi[1,1,1])

lenx = 0.5;

epsilon2 = 1.;

va = DIVAnd.DIVAndrunfi(mask,(pm,pn,po),(xi,yi,zi),(x,y,z),f,lenx,epsilon2)
```

I have also tryed to transpose some of the fields (as in DIVAnd.py) but I still obtain a zero output

```
va = DIVAnd.DIVAndrunfi(np.transpose(mask),(np.transpose(pm),np.transpose(pn),np.transpose(po)),
(np.transpose(xi),np.transpose(yi),np.transpose(zi)),
(x,y,z),f,lenx,epsilon2)
```

I am supposing there is a different way in which JULIA and python order the axes, I will do other tests swapping them.

**Comment by ctroupin** [comment]
Quick try: could you replace:
```julia
pm = np.ones(xi.shape) / (xi[1,2,1]-xi[1,1,1])
pn = np.ones(xi.shape) / (yi[2,1,1]-yi[1,1,1])
```
with
```julia
pm = np.ones(xi.shape) / (xi[2,1,1]-xi[1,1,1])
pn = np.ones(xi.shape) / (yi[1,2,1]-yi[1,1,1])
```

**Comment by ecutolo** [comment]
In the way you said pm and pn gives infinity while in the way I did the results are the same as DIVAnd with julia anyway I think I found a solution. It was a problem with the axes ordering using the numpy function swapaxes instead of transpose it works also with 3D fields. There is a pull-request pending.  I did not check with 4D yet.

**Comment by Alexander-Barth** [comment]
Did you see this note of meshgrid? (https://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html)

In the 2-D case with inputs of length M and N, the outputs are of shape (N, M) for ‘xy’ indexing and (M, N) for ‘ij’ indexing. In the 3-D case with inputs of length M, N and P, outputs are of shape (N, M, P) for ‘xy’ indexing and (M, N, P) for ‘ij’ indexing. 

Does it work when you use  ‘ij’ indexing and a suitable definition of pm, pn, ...

```python
pm = np.ones(xi.shape) / (xi[1,0,0]-xi[0,0,0])
# [...]
```

**Comment by ecutolo** [comment]
Ok yes, using the 'ij' indexing it works if you do not transpose the matrix nor use the swapaxes inside the DIVAnd wrapper function.  This last in facts should be modified anyway removing the np.transpose and just preserving the masking:

```
def DIVAnd(mask, pmn, xi, x, f, corlen, epsilon2):
    va = D.DIVAndrunfi(mask,pmn,xi,x, f, corlen, epsilon2)
    return np.ma.MaskedArray(va, np.logical_not(mask))
```

**Comment by Alexander-Barth** [comment]
This file is an example for applying DIVAnd.py in 3D:
https://github.com/gher-ulg/DIVAnd.py/blob/88787becfff206e247dbee24a74963062050fe5e/examples/DIVAnd_3d.py

As you will see, there are 2 ways to call DIVAnd:
* either directly via pyjulia
* or via the wrapper: https://github.com/gher-ulg/DIVAnd.py/blob/88787becfff206e247dbee24a74963062050fe5e/examples/DIVAnd_3d.py#L7

Both variants do actually work for 3D.

I made the wrapper in an attempt to make DIVAnd more natural for python users because the default order of the dimensions is usually (depth, latitude, longitude, at least when I read a NetCDF file in python, or C/C++,...) while the order of Julia (and Fortran, Octave, ...) is longitude, latitude and depth. But this creates more confusion that it is actually worth. Also, numpy supports both storage orders.

So what is will do, it to skip the wrapper (what is actually what you did in the code sample in this issue) DIVAnd.py and use the first variant in the example file:

https://github.com/gher-ulg/DIVAnd.py/blob/88787becfff206e247dbee24a74963062050fe5e/examples/DIVAnd_3d.py#L32
 
The julia code DIVAnd has also grown considerably, and it would not be feasible to have a wrapper which transpose the arguments of all functions and at the same time pyjulia made it quite convenient to call julia code directly from python.
